l_polish:
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2.0 - Vysoká"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1.5 - Střední"
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1.0 - Žádná"
 OPTION_SAVE_FILE_TEXT: "Text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Zkomprimovaný binární soubor"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Zkomprimovaný ový soubor"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Pokročilé"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Obecné"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Cyklus dne a noci"
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS: "Oznámení"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portréty"
 SETTINGS_CATEGORY_LANGUAGE: "Jazyk"
 SETTINGS_CATEGORY_MAPMODES: "Módy mapy"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Ovládání mapy"
 SETTINGS_CATEGORY_MFX: "Hudba"
 SETTINGS_CATEGORY_OUTLINER: "Rozložení"
 SETTINGS_CATEGORY_SAVE_GAMES: "Uložit Hry"
 SETTINGS_CATEGORY_SFX: "Zvukové efekty"
 SETTINGS_CATEGORY_TOOLTIPS: "Nastavení nápovědy"
 SETTING_AMBIENT: "Ambience"
 SETTING_AMBIENT_TOOLTIP: "#T Hlasitost prostředí\n#!Nastaví hlasitost prostředí."
 SETTING_AUTOSAVE_TO_CLOUD: "Automatické uložení do cloudu"
 SETTING_BUILDINGS_CUTOFF: "Odstranit vzdálené budovy"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nZobrazuje méně budov na mapě, čím dál jsou od kamery.\n\nPovolení může zvýšit výkon."
 SETTING_DAYNIGHT_CYCLE: "Povolit cyklus dne a noci"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nPovoluje cyklus dne a noci pro pohyb slunce."
 SETTING_DAYNIGHT_SET_TIME: "Povolit ruční čas"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nNastaví čas dne na určenou hodinu.\n\n#!Přepíše nastavení rychlosti simulace a synchronizuje místní čas."
 SETTING_DAYNIGHT_SPEED: "Rychlost simulace"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nJak rychle bude čas cyklit mezi dnem a nocí.#"
 SETTING_DAYNIGHT_SYSTEMTIME: "Povolit synchronizaci místního času"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSynchronizuje rychlost cyklu dne a noci a čas s místním časem počítače.\n\n#!Přepíše nastavení rychlosti simulace."
 SETTING_MAP_MODE_DELAY: "Zpoždění Módu mapy"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Zpoždění před přepnutím na nový Mód mapy, v sekundách"
 SETTING_MAP_MODE_FADE_IN: "Mód mapy Fade-in"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Čas pro nový Mód mapy, aby se vybledl po tom, co starý vybledl, v sekundách"
 SETTING_MAP_MODE_FADE_OUT: "Mód mapy Fade-out"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Čas pro aktuální Mód mapy, aby vybledl po zpoždění Módu mapy, když je třeba aplikovat nový Mód mapy, v sekundách"
 SETTING_MAP_TOOLTIP_DELAY: "Zpoždění nápovědy mapy"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nNastaví zpoždění před zobrazením nápovědy mapy."
 SETTING_MUSIC: "Hudba"
 SETTING_MUSIC_STINGERS: "Hudební výstřely"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Krátké hudební fráze pro zlepšení herního zážitku"
 SETTING_MUSIC_TOOLTIP: "#T Hlasitost hudby\n#!Nastaví hlasitost hudby."
 SETTING_OCCUPATION_STRIPES: "Pruhové vizuály povolání"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nPovolit barevné pruhy jako vizuály povolání na mapě namísto textur vlajek zemí."
 SETTING_PAUSE_ON_EVENT: "Pozastavit a popup na události"
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS: "$SETTING_PAUSE_ON_EVENT$ (pouze pro jednoho hráče)"
 SETTING_PAUSE_ON_EVENT_TOOLTIP: "#T $SETTING_PAUSE_ON_EVENT$#!\nZastaví hru a zobrazí popup, když dojde k události."
 SETTING_PORTRAIT_RENDER_SCALE: "Měřítko renderování portrétu"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nZlepšuje úroveň detailů portrétu postavy zvětšením výsledků renderování, na úkor některého výkonu renderování."
 SETTING_SAVE_FILE_FORMAT: "Výchozí formát uložení"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Tato volba je přepsána v režimu Ironman, Cloud a Debug"
 SETTING_SHADER_QUALITY: "Kvalita shaderů"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Kvalita shaderů\n#!Určuje kvalitu různých shaderů a efektů.\n\n#T Vysoká:#! Zlepšuje kvalitu některých shaderových efektů na úkor výkonu.\n\n#T Střední:#! Výchozí nastavení pro zamýšlený grafický zážitek.\n\n#T Nízká:#! Toto nastavení je určeno pro slabší stroje a není doporučeno kvůli ztrátě vizuální kvality. Mnohé shadery jsou zjednodušeny pro zvýšení grafického výkonu."
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Oznámení vlevo od rozložení"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nUmístěte Oznámení do levé části rozložení"
 SETTING_SHOW_NUDITY: "Zobrazit nahotu"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nNastaví, zda mohou být postavy zobrazeny nahé."
 SETTING_SOUNDTRACK: "Hudba v pozadí"
 SETTING_SOUNDTRACK_TOOLTIP: "Obecná hudba v pozadí"
 SETTING_SUNRISE_SET_TIME_HOUR: "Ruční čas hodiny"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nZamkne čas na tuto hodinu.\n\n#!Používá se pouze při povoleném ručním čase#"
 SETTING_SUNRISE_TIME: "Čas východu slunce"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nHodina, kdy slunce vyjde.\n\n#!Používá se pouze při synchronizaci s místním časem. #!"
 SETTING_SUN_DURATION: "Hodiny slunce"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nPočet hodin slunce za den."
 SETTING_TOOLTIP_DELAY: "Zobrazit zpoždění"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nNastaví zpoždění před tím, než se nápověda zobrazí, když je kurzor nad prvkem s nápovědou."
 SETTING_TOOLTIP_LOCK_TIME: "Zpoždění uzamčení"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nNastaví zpoždění před uzamčením nápověd."
 SETTING_TOOLTIP_MODE: "Režim nápovědy"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Akční uzamčení (Kotva myši)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Akční uzamčení"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Časování uzamčení (Kotva myši)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Časování nebo akční uzamčení"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Časování uzamčení"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendence myši"
 SETTING_TOOLTIP_MODE_NO_LOCK: "Žádné uzamčení"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nVyberte, jak by se měly nápovědy uzamykat:\n   #b Tendence myši#! - Uzamkne ji, pokud posunete myš směrem k nápovědě.\n   #b Časování uzamčení#! - Uzamkne ji po nastaveném čase.\n   #b Akční uzamčení#! - Uzamkne ji prostředním tlačítkem myši.\n   #b Časování nebo akční uzamčení#! - Může použít buď Časování uzamčení nebo Akční uzamčení."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Zamčené otevřené zpoždění"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nNastaví zpoždění před tím, než jsou nápovědy uzamčeny, když je jiná nápověda již otevřená."
 SETTING_TOOLTIP_UNLOCK_TIME: "Zpoždění odemčení"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nNastaví zpoždění před odemčením nápověd."
 SETTING_VALUE_HOURS: "$VALUE|0$ Hodiny"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 building_sets_themes: "Sada budov"
 color_blind_mode_test: "Test"
 papermap_theme: "Papírová mapa"
 papermap_theme_desc: "Toto je mapa, kterou vidíte, když jste oddáleni."
 table_asset_1_theme: "Objekt na stole (levý horní roh)"
 table_asset_1_theme_desc: "Objekt zobrazený v levém horním rohu tabulky vedle mapy při oddálení."
 table_asset_2_theme: "Objekt na stole (pravý horní roh)"
 table_asset_2_theme_desc: "Objekt zobrazený v pravém horním rohu tabulky vedle mapy při oddálení."
 table_asset_3_theme: "Objekt na stole (spodní levý roh)"
 table_asset_3_theme_desc: "Objekt zobrazený v dolním levém rohu tabulky vedle mapy při oddálení."
 table_asset_4_theme: "Objekt na stole (spodní pravý roh)"
 table_asset_4_theme_desc: "Objekt zobrazený v pravém dolním rohu tabulky vedle mapy při oddálení."
 table_asset_cloth_theme: "Ubrus na stole"
 table_asset_cloth_theme_desc: "Látka, na které leží mince."
 table_top_theme: "Hlava stolu"
 table_top_theme_desc: "Pokud se oddálíte co nejvíce na mapě, můžete vidět tuto tabulku nahoře a dole na obrazovce."
 ui_skin_theme: "Uživatelské rozhraní"
 ui_skin_theme_desc: "Tlačítka, rámy, okna, záhlaví atd. ve hře."
 RESET_SETTINGS_TO_DEFAULT: "Obnovit na #b výchozí hodnoty#!"
 SETTING_CULTURE_RELIGION_MINORITY_BLEND: "Směs barev menšin v mapovém režimu kultura/náboženství"
 SETTING_CULTURE_RELIGION_MINORITY_BLEND_TOOLTIP: "#T $SETTING_CULTURE_RELIGION_MINORITY_BLEND$#!\nPoužít staré mísení barev menšin místo pruhů v mapových přehledech kultury nebo náboženství."
 SETTING_EVENT_OPTION_TEXT_ALIGNMENT: "Zarovnání textu možností událostí"
 OPTION_LEFT: "Vlevo"
 OPTION_CENTERED: "Na střed"
 OPTION_RIGHT: "Vpravo"
 DYNAMIC_THEME: "Dynamický"
 DYNAMIC_THEME_DESC: "Automaticky vybere tému [ThemeCategory.GetName|v] na základě hrané [Concept('concept_country','země')]"
 main_menu_image_theme: "Obrázek hlavního menu"
 main_menu_image_theme_desc: "Animovaný obrázek zobrazovaný jako pozadí hlavního menu."
 SETTING_TELEMETRY_DATA: "Telemetrická data" # todo: NEW TRANSLATION
